- name: Creating the directories required for prometheus
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    with_items:
     -  "{{prometheus_archieve_file_download_directory}}"
     -  "{{prometheus_configuration_directory}}"


- name: Downloading the Prometheus archive file
  get_url:
    url: "{{prometheus_download_url}}"
    dest: "{{prometheus_archieve_file_download_directory}}"
    owner: root
    group: root


- name: Extracting the prometheus archieve file
  unarchive:
    src: "{{ prometheus_archieve_file_download_directory }}/{{ prometheus_archive_file_name }}"
    dest: "{{prometheus_archieve_file_download_directory}}"
    owner: root
    group: root
    remote_src: yes


- name: Copying the prometheus binary to /usr/local/bin
  copy:
   src: "{{prometheus_archieve_file_download_directory}}/{{prometheus_folder_name}}/prometheus"
   dest: "{{prometheus_binary_location}}"
   owner: root
   group: root
   mode: '111'
   remote_src: yes

- name: Copying the prometheus configuration file to /etc/prometheus
  copy:
   src: "config/prometheus.yml"
   dest: "{{ prometheus_configuration_directory }}/prometheus.yml"
   owner: root
   group: root
  notify:
